### ISSUE TITLE
buffer overflow

### ISSUE THREAD

**Issue by slava-vishnyakov** [mailgun/kafka-pixy#76]
```
#!/bin/bash

## Push test data

function pushit() {
    curl --silent -X POST "http://localhost:19092/topics/foo/messages?sync" -H "Content-Type: text/plain" -d "blah blah blah {}"
}
export -f pushit
time (seq 1000 | parallel -j100 pushit)

## Reset

curl -X POST -H'Content-Type: application/json' -d'[{"partition":0,"offset":0}]' 'http://localhost:19092/topics/foo/offsets?group=bar'
echo
sleep 10

## Pull

function pullit() {
    curl -G --silent 'http://localhost:19092/topics/foo/messages?group=bar' | tr "\n" " "
    echo
}
export -f pullit
time (seq 1000 | parallel -j100 pullit)

```

So, I'm running then the "pull" step separately (I'm trying to pull the data from Kafka-Pixy with 100 parallel readers) and sometimes I get this:

```
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow" }
```

as a response.

**Comment by horkhe** [comment]
First of all you need to know that **kafka-pixy** is highly parallel it implements many internal goroutines communicating via channels when it makes sense to have a buffered channel of a size greater than 1, the size of the buffer is given by [Config.Consumer.ChannelBufferSize](https://github.com/mailgun/kafka-pixy/blob/master/config/config.go#L49) it default to [64](https://github.com/mailgun/kafka-pixy/blob/master/config/config.go#L80).

One of the cases when you can overflow an internal buffer is when you generate requests faster than kafka-pixy can handle at a time. In your case that happens because you generate more than buffer size requests almost simultaneously to a **cold** kafka-pixy instance, meaning that it has not yet registered a group member with Kafka. It does that when first request for the group comes to kafka-pixy and that might take some time.

Since under normal circumstances threads do not make as many requests simultaneously and warmed up kafka-pixy is capable of processing them much faster you should observe higher throughput.

If with your workload on warmed up kafka-pixy you still observe _buffer overflow_ errors, I suggest increasing the aforementioned consumer buffer size. Which reminds me that I should probably implement #16 to make it easy for you.

**Comment by slava-vishnyakov** [comment]
It would be great to have a link to this discussion in error, maybe like this:

```{   "error": "\u003c/cons[0]/G:bar[12]/T:foo[0]\u003e buffer overflow, see: https://github.com/mailgun/kafka-pixy/issues/76#issuecomment-245696032" }```

And maybe `buffer overflow` can be a little more verbose? Like what kind of buffer? :) Because it sounds really scary.. like remote-code-execution-scary :) Which shouldn't be possible with go, but scary anyway :)

So, basically, that means that I should do one request first and only then run parallel requests? Does that mean that I would not be able to have more than 64 connections unless I change config?

**Comment by horkhe** [comment]
You probably right, I will change that to something like `Too many concurrent requests`.

As for how to run tests. Here is the thing. When the first consume request from a particular consumer group arrives, kafka-pixy joins the consumer group as a member in ZooKeeper. When the first request to a particular topic from a particular consumer group arrives kafka-pixy subscribes the member to the topic in ZooKeeper. Subscription update results in topic partition rebalancing. Rebalancing also happens when other consumer group members subscribe/unsubscribe to the topic. During rebalancing kafka-pixy does not consume messages until it can claim the partitions assigned to it in ZooKeeper. All that takes time. As a result during rebalancing the throughput is very low.

In your tests you basically hit kafka-pixy during rebalancing phase, as a result the results that you get do not correspond to normal operation when all members have long joined the consumer group and consuming messages. If you want to test throughput, then you should keep testing beyond the initial several seconds.

**Comment by slava-vishnyakov** [comment]
Great! Thanks for the detailed explanation. I'll re-try once again with newer version and slow start.

**Comment by slava-vishnyakov** [comment]
Also works exactly like #77 - 50 concurrent, 20 second sleep before reset - everything is fine!
